#previews:
#  generation: automatic

services:
  - type: web
    name: pdf-unlocker
    repo: https://github.com/munirmardinli/pdf-unlocker
    branch: main
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: out
    pullRequestPreviewsEnabled: false
    autoDeploy: true
    #ipAllowList: []
    renderSubdomainPolicy: disabled
    domains:
      - pdf.mardinli.dev
    envVars:
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
